Repository evannetwork/api-blockchain-core, pull requests merged in 2019-12, with the labels that each got.

#32 update naming of verifications
  VERSIONS.md
  docs/contracts/container.rst
  docs/contracts/rights-and-roles.rst
  docs/profile/verification-usage-examples.rst
  src/contracts/digital-twin/container.spec.ts
  src/contracts/digital-twin/container.ts
  src/contracts/digital-twin/digital-twin.spec.ts
Labels: documentation

#33 Core 713 blockchain core feedback
  docs/profile/onboarding.rst
  src/contracts/sharing.ts
  src/keyExchange.spec.ts
  src/onboarding.spec.ts
  src/onboarding.ts
  src/profile/profile.spec.ts
  src/profile/profile.ts
  src/test/test-utils.ts
Labels: api, documentation

#40 Feature/core 729 did registry and resolver
  .gitignore
  VERSIONS.md
  docs/Makefile
  docs/blockchain/executor-agent.rst
  docs/blockchain/executor-wallet.rst
  docs/blockchain/index.rst
  docs/blockchain/signer-identity.rst
  docs/profile/did-resolver.rst
  docs/profile/index.rst
  package.json
  src/common/utils.ts
  src/config-core.ts
  src/config-testcore.ts
  src/contracts/digital-twin/container.spec.ts
  src/contracts/digital-twin/container.ts
  src/contracts/executor-agent.spec.ts
  src/contracts/executor-wallet.spec.ts
  src/contracts/signer-identity.spec.ts
  src/contracts/signer-identity.ts
  src/did/did-resolver.spec.ts
  src/did/did-resolver.ts
  src/encryption/encryption-wrapper.spec.ts
  src/index.ts
  src/payments.spec.ts
  src/profile/business-center-profile.spec.ts
  src/profile/business-center-profile.ts
  src/profile/profile.ts
  src/runtime.ts
  src/test/test-utils.ts
  tsconfig_husky.json
  tslint.json
Labels: api, documentation

#36 Feature/core 602 handle keys based on identities
  .travis.yml
  VERSIONS.md
  docs/profile/mailbox.rst
  src/contracts/signer-identity.spec.ts
  src/dfs/ipld.ts
  src/encryption/encryption-wrapper.spec.ts
  src/index.ts
  src/mailbox.ts
  src/test/accounts.ts
  src/test/test-utils.ts
Labels: api, documentation

#41 add `getService`, `setService` to `DidResolver`
  VERSIONS.md
  docs/profile/did-resolver.rst
  src/did/did-resolver.spec.ts
  src/did/did-resolver.ts
Labels: api, documentation

#43 remove chunked encryption
  src/encryption/aes-blob.ts
Labels: api
