Repository evannetwork/api-blockchain-core, pull requests merged in 2020-02, with the labels that each got.

#67 fix onboarding with identity
  src/onboarding.ts
Labels: api

#68 Feature/core 952 fix misleading error message on wrong account in signer identity
  VERSIONS.md
  src/contracts/signer-identity.spec.ts
  src/contracts/signer-identity.ts
Labels: api

#69 fix digital template plugins are not checked for valid ajv schema
  VERSIONS.md
  src/contracts/digital-twin/digital-twin.spec.ts
  src/contracts/digital-twin/digital-twin.ts
Labels: api

#74 add support for custom DID registries for DID tests
  VERSIONS.md
  docs/profile/did.rst
  src/did/did.spec.ts
  src/did/did.ts
Labels: api

#72 fix internal signer when creating offline profile
  src/onboarding.ts
  src/runtime.ts
Labels: api

#73 Feature/core 901 update did public key handling
  VERSIONS.md
  docs/profile/did.rst
  src/did/did.spec.ts
  src/did/did.ts
  src/vc/vc.spec.ts
  src/vc/vc.ts
  src/verifications/verifications.ts
Labels: api, documentation

#77 Feature/core 734 create vc documents when issuing a verification
  VERSIONS.md
  docs/profile/verifications.rst
  src/runtime.ts
  src/vc/vc.ts
  src/verifications/verifications.spec.ts
  src/verifications/verifications.ts
Labels: api, documentation

#79 fix profile creation docs
  docs/getting-started.rst
Labels: documentation

#78 Feature/core 921 fix special character handling
  VERSIONS.md
  src/contracts/digital-twin/container.spec.ts
  src/contracts/digital-twin/digital-twin.ts
  src/contracts/sharing.ts
  src/dfs/ipfs.spec.ts
  src/dfs/ipfs.ts
  src/onboarding.ts
  src/verifications/verifications.ts
Labels: api

#80 add `member-ordering` rule and update code
  .eslintrc.js
  VERSIONS.md
  package.json
  src/contracts/digital-twin/container.ts
  src/contracts/digital-twin/digital-twin.ts
  src/contracts/wallet.ts
  src/dfs/ipfs.ts
  src/dfs/ipld.ts
  src/did/did.ts
  src/encryption/aes-blob.ts
  src/keyExchange.ts
  src/onboarding.ts
  src/profile/profile.ts
  src/verifications/verifications.ts
Labels: api

#66 parallize sharing and unsharing
  VERSIONS.md
  src/contracts/digital-twin/container.ts
Labels: api

#71 update docs for getSharings and getSharingsFromContracts
  docs/contracts/sharing.rst
  src/contracts/digital-twin/container.spec.ts
  src/contracts/digital-twin/digital-twin.spec.ts
Labels: documentation
