Repository evannetwork/api-blockchain-core, pull requests merged in 2020-01, with the labels that each got.

#57 Feature/core 633 handle container based profile properties
  .travis.yml
  VERSIONS.md
  docs/conf.py
  docs/profile/vc.rst
  src/common/utils.ts
  src/contracts/sharing.spec.ts
  src/did/did.spec.ts
  src/keyExchange.spec.ts
  src/onboarding.ts
  src/profile/profile.spec.ts
  src/runtime.ts
  src/test/accounts.ts
  src/test/test-utils.ts
  src/vc/vc.spec.ts
  src/vc/vc.ts
  src/verifications/verifications.spec.ts
Labels: api

#56 Feature/core 856 generate dids onboarding
  VERSIONS.md
  docs/conf.py
  docs/profile/vc.rst
  package.json
  src/common/utils.ts
  src/contracts/sharing.spec.ts
  src/did/did.spec.ts
  src/did/did.ts
  src/keyExchange.spec.ts
  src/onboarding.spec.ts
  src/onboarding.ts
  src/profile/profile.spec.ts
  src/runtime.ts
  src/test/accounts.ts
  src/test/test-utils.ts
  src/vc/vc.spec.ts
  src/vc/vc.ts
  src/verifications/verifications.spec.ts
Labels: api

#58 update root verification handling to use genesis account
  VERSIONS.md
  src/config-core.ts
  src/config-testcore.ts
  src/verifications/verifications.spec.ts
  src/verifications/verifications.ts
Labels: api

#60 use external twin sample for documentation
  docs/contracts/digital-twin-usage-examples.rst
  docs/contracts/digital-twin.rst
Labels: documentation

#59 fix behavior of `DataContract` for unencrypted data
  VERSIONS.md
  src/contracts/data-contract/data-contract.spec.ts
  src/contracts/data-contract/data-contract.ts
Labels: api

#61 Core 896 have `get gas price` at `signer interface`
  VERSIONS.md
  docs/blockchain/signer-identity.rst
  src/contracts/signer-identity.spec.ts
  src/contracts/signer-identity.ts
Labels: api

#63 Feature/core 867 change did allowed key type
  .travis.yml
  VERSIONS.md
  docs/profile/verifications.rst
  src/contracts/digital-twin/digital-twin.ts
  src/did/did.spec.ts
  src/did/did.ts
  src/verifications/verifications.spec.ts
  src/verifications/verifications.ts
Labels: api

#64 Feature/core 892 add identity owner mapping
  .travis.yml
  docs/profile/verifications.rst
  src/verifications/verifications.spec.ts
Labels: api, documentation

#65 update `eslint` related modules' versions
  package.json
Labels: api
