Repository evannetwork/api-blockchain-core, pull requests merged in 2020-04, with the labels that each got.

#103 Feature/core 1059 update documentation for identity based profiles
  docs/_static/Identity_based_profile.png
  docs/blockchain/description.rst
  docs/blockchain/executor-agent.rst
  docs/blockchain/executor-wallet.rst
  docs/blockchain/name-resolver.rst
  docs/blockchain/payments.rst
  docs/blockchain/votings.rst
  docs/blockchain/wallet.rst
  docs/common/utils.rst
  docs/contracts/base-contract.rst
  docs/contracts/container.rst
  docs/contracts/data-contract.rst
  docs/contracts/digital-twin.rst
  docs/contracts/rights-and-roles.rst
  docs/contracts/service-contract.rst
  docs/contracts/sharing.rst
  docs/dfs/ipld.rst
  docs/getting-started.rst
  docs/identity_based_profile.rst
  docs/index.rst
  docs/profile/business-center-profile.rst
  docs/profile/did.rst
  docs/profile/key-exchange.rst
  docs/profile/mailbox.rst
  docs/profile/profile.rst
  docs/profile/verifications.rst
  src/common/utils.ts
  src/contracts/base-contract/base-contract.ts
  src/contracts/data-contract/data-contract.ts
  src/contracts/digital-twin/container.ts
  src/contracts/rights-and-roles.ts
  src/contracts/service-contract/service-contract.ts
  src/contracts/sharing.ts
  src/contracts/wallet.ts
  src/did/did.ts
  src/encryption/aes-blob.ts
  src/encryption/aes-ecb.ts
  src/encryption/aes.ts
  src/keyExchange.ts
  src/mailbox.ts
  src/name-resolver.ts
  src/payments.ts
  src/profile/business-center-profile.ts
  src/profile/profile.ts
  src/shared-description.ts
  src/verifications/verifications.ts
  src/votings/votings.ts
Labels: documentation

#104 send EvanIdentity as header by generating the evan auth message
  VERSIONS.md
  docs/common/utils.rst
  src/common/utils.ts
Labels: api

#107 skip `vc` creation when `setVerificationAndVc` is used without useIde…
  VERSIONS.md
  src/verifications/verifications.spec.ts
  src/verifications/verifications.ts
Labels: api

#109 Feature/core 1129 identity access
  .github/workflows/test.yml
  VERSIONS.md
  docs/profile/identity.rst
  src/contracts/signer-identity.ts
  src/identity/identity.spec.ts
  src/identity/identity.ts
  src/runtime.ts
  src/verifications/verifications.ts
Labels: api, documentation
